pool: Default

trigger:
-  main
- feature/*

stages:
  - stage: tflint
    displayName: tflint
    jobs:
      - job: tflint
        steps:
        - task: PowerShell@2
          displayName: tflint
          inputs:
            targetType: 'inline'
            script: 'tflint --recursive'

  - stage: tfsec
    displayName: tfsec
    jobs:
      - job: tfsec
        steps:
        - task: PowerShell@2
          displayName: tfsec
          inputs:
            targetType: 'inline'
            script: 'tfsec .'

  - stage: checkov
    displayName: checkov
    jobs:
      - job: checkov
        steps:
        - task: PowerShell@2
          displayName: ckeckov
          inputs:
            targetType: 'inline'
            script: 'checkov -d .'